### PR TITLE
Feature/apiddubny 59 cleanup attribute names and descriptions

### PR DESCRIPTION
**Pull request by apiddubny**
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/233)

### CODE REVIEW

**Comment by alexazarh** [comment]
*[package/cloudshell/cp/azure/azure_shell.py, line 201 at r4](https://reviewable.io:443/reviews/qualisystems/azure-shell/233#-KYiu79j8vG4ofeBgxvJ:-KYiu79j8vG4ofeBgxvK:b-hld8lo) ([raw file](https://github.com/qualisystems/azure-shell/blob/0c9a301d730582d4cb06d9ed3ace110105fcce71/package/cloudshell/cp/azure/azure_shell.py#L201)):*
> ```Python
>                     self._set_decrypted_azure_secret(cloudshell_session=cloudshell_session,
>                                                      cloud_provider_model=cloud_provider_model,
>                                                      logger=logger)
> ```

Instead of adding this 2 lines of code to all the methods in this class why not handle the decryption in the converter?
Than we only need to add the creation of the cloudshell_session and pass it to the converter...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/233)*

**Comment by alexazarh** [comment]
Reviewed 7 of 8 files at r1.
Review status: 2 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/233)*

**Comment by apiddubny** [comment]
Review status: 2 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package/cloudshell/cp/azure/azure_shell.py, line 201 at r4](https://reviewable.io:443/reviews/qualisystems/azure-shell/233#-KYiu79j8vG4ofeBgxvJ:-KYmPtglbrzNpcUGeNHY:bpxssvr) ([raw file](https://github.com/qualisystems/azure-shell/blob/0c9a301d730582d4cb06d9ed3ace110105fcce71/package/cloudshell/cp/azure/azure_shell.py#L201)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

Instead of adding this 2 lines of code to all the methods in this class why not handle the decryption in the converter?
Than we only need to add the creation of the cloudshell_session and pass it to the converter...
</blockquote></details>

what if there will be methods which will use cloud provider model but without azure secret attribute? in such cases they will do unnecessary additional request

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/233)*

**Comment by alexazarh** [comment]
*[package/cloudshell/cp/azure/azure_shell.py, line 201 at r4](https://reviewable.io:443/reviews/qualisystems/azure-shell/233#-KYiu79j8vG4ofeBgxvJ:-KYmn1OEJJGjTHlDFFUA:b-m85zpg) ([raw file](https://github.com/qualisystems/azure-shell/blob/0c9a301d730582d4cb06d9ed3ace110105fcce71/package/cloudshell/cp/azure/azure_shell.py#L201)):*
<details><summary><i>Previously, apiddubny (Anthony Piddubny) wrote…</i></summary><blockquote>

what if there will be methods which will use cloud provider model but without azure secret attribute? in such cases they will do unnecessary additional request
</blockquote></details>

Do we have such methods at the moment? I think we dont. We can add an optional variable in the convert method that will specify if we want to decrypt the pass or not. Default should be to decrypt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/233)*

**Comment by apiddubny** [comment]
Review status: 2 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package/cloudshell/cp/azure/azure_shell.py, line 201 at r4](https://reviewable.io:443/reviews/qualisystems/azure-shell/233#-KYiu79j8vG4ofeBgxvJ:-KYoetKavDIfDSDEtVIk:b-896fix) ([raw file](https://github.com/qualisystems/azure-shell/blob/0c9a301d730582d4cb06d9ed3ace110105fcce71/package/cloudshell/cp/azure/azure_shell.py#L201)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

Do we have such methods at the moment? I think we dont. We can add an optional variable in the convert method that will specify if we want to decrypt the pass or not. Default should be to decrypt.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/233)*

**Comment by alexazarh** [comment]
Reviewed 4 of 8 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/233)*

**Pull request merged**
