### PR TITLE
Feature/apiddubny 27 28 deployed app model vm credentionals

### PR DESCRIPTION
**Pull request by apiddubny**
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/76)

### CODE REVIEW

**Comment by GilGald** [comment]
*[package/cloudshell/cp/azure/domain/services/key_pair.py, line 51 at r2](https://reviewable.io:443/reviews/qualisystems/azure-shell/76#-KV0di6C392JOn1HrsVO:-KV0di6C392JOn1HrsVP:bj88eqj) ([raw file](https://github.com/qualisystems/azure-shell/blob/1f94d38fd4eba610e15d35ad0775857fc95ba03d/package/cloudshell/cp/azure/domain/services/key_pair.py#L51)):*
> ```Python
>                                             file=key_pair.private_key)
> 
>     def get_key_pair(self, account_key, storage_name):
> ```

It should be moved to the storage service (talk to me)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by GilGald** [comment]
*[package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, line 74 at r2](https://reviewable.io:443/reviews/qualisystems/azure-shell/76#-KV0e-HAHd2O42OVLHLP:-KV0e-HAHd2O42OVLHLQ:b30ofll) ([raw file](https://github.com/qualisystems/azure-shell/blob/1f94d38fd4eba610e15d35ad0775857fc95ba03d/package/cloudshell/cp/azure/domain/services/virtual_machine_service.py#L74)):*
> ```Python
>         :param image_sku:
>         :param image_version:
>         :param vm_credentials:
> ```

Add more information on doc string  with type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by GilGald** [comment]
*[package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, line 38 at r2](https://reviewable.io:443/reviews/qualisystems/azure-shell/76#-KV0fb15-wZ99aB9_-RF:-KV0fb15-wZ99aB9_-RG:b-y0ur93) ([raw file](https://github.com/qualisystems/azure-shell/blob/1f94d38fd4eba610e15d35ad0775857fc95ba03d/package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py#L38)):*
> ```Python
>         self.tags_service = tags_service
> 
>     def _get_image_operation_system(self, cloud_provider_model, azure_vm_deployment_model, compute_client):
> ```

same code in vm service

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by GilGald** [comment]
*[package/cloudshell/cp/azure/models/authorized_key.py, line 7 at r2](https://reviewable.io:443/reviews/qualisystems/azure-shell/76#-KV0gCS6YZp9pfN6ISvR:-KV0gCS6YZp9pfN6ISvS:b5uyhnx) ([raw file](https://github.com/qualisystems/azure-shell/blob/1f94d38fd4eba610e15d35ad0775857fc95ba03d/package/cloudshell/cp/azure/models/authorized_key.py#L7)):*
> ```Python
>         :param key_data: (str) SSH public key
>         """
>         self.path_to_key = path_to_key
> ```

What's that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by GilGald** [comment]
Reviewed 6 of 12 files at r1, 1 of 1 files at r2.
Review status: 7 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by alexazarh** [comment]
Reviewed 2 of 12 files at r1, 4 of 10 files at r7, 2 of 2 files at r8, 1 of 2 files at r10.
Review status: 10 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 67 at r10](https://reviewable.io:443/reviews/qualisystems/azure-shell/76#-KV_p7Jc365vnD5kqhnZ:-KV_p7Jc365vnD5kqhn_:bz825ri) ([raw file](https://github.com/qualisystems/azure-shell/blob/c1e5bc23f2ee926267a55f362e8166f23bbca77a/package/cloudshell/cp/azure/domain/services/storage_service.py#L67)):*
> ```Python
>         :return: azure.storage.file.FileService instance
>         """
>         cached_key = (group_name, storage_name)
> ```

cached_key is shared between threads so I think we need to use locking to make it thread safe

---

*[package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, line 74 at r2](https://reviewable.io:443/reviews/qualisystems/azure-shell/76#-KV0e-HAHd2O42OVLHLP:-KV_ou1BU_AKkJCoWQL-:b-ikgd90) ([raw file](https://github.com/qualisystems/azure-shell/blob/1f94d38fd4eba610e15d35ad0775857fc95ba03d/package/cloudshell/cp/azure/domain/services/virtual_machine_service.py#L74)):*
<details><summary><i>Previously, GilGald wrote…</i></summary>
> Add more information on doc string  with type.
</details>
please add object types in doc string for this method (create_cm)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by alexazarh** [comment]
Reviewed 2 of 3 files at r11.
Review status: 10 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by alexazarh** [comment]
Reviewed 1 of 12 files at r1, 1 of 5 files at r4, 2 of 10 files at r7, 1 of 3 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by GilGald** [comment]
Reviewed 1 of 12 files at r1, 1 of 5 files at r4, 5 of 10 files at r7, 2 of 2 files at r8, 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by alexazarh** [comment]
Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Comment by alexazarh** [comment]
Reviewed 5 of 6 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/76)*

**Pull request merged**
