### PR TITLE
server uses PrepareSubnetParams.IsPublic to describe public subnets, …

### PR DESCRIPTION
**Pull request by nahumtimerman**
…not subnet attributes.

Root issue was that we dont use "subnet attributes" to describe certain things (such as cidr, ispublic)
instead, we have special properties for that.

Reason was "working" in 9.3 due to 9.3 not actually receiving P2P subnet requests, but instead using default subnet, due to bug in server code.

 bug: 
http://team:8080/tfs/Quali-Collection/QualiSystems/_workitems/edit/178555 Azure: Reserve fails for Blueprint that has 2 Azure apps with P2P connectivity when both apps has "Add Public IP" set to True.

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/629)

### CODE REVIEW

**Review by apiddubny — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/629)* status: all files reviewed, 1 unresolved discussion (waiting on @Costya-Y and @nahumtimerman)

___
*[package/cloudshell/cp/azure/domain/vm_management/operations/PrepareSandboxInfraOperation.py, line 440 at r1](https://reviewable.io/reviews/qualisystems/azure-shell/629#-MMHAk7u34YL-c-2VK-O:-MMHAk7u34YL-c-2VK-P:b87xlx7) ([raw file](https://github.com/qualisystems/azure-shell/blob/1fffab7d2097f83cb960b313a79e5a5d52c51743/package/cloudshell/cp/azure/domain/vm_management/operations/PrepareSandboxInfraOperation.py#L440)):*
> ```Python
> 
>         # block access from internet to private subnets
>         private_subnets = [s for s in subnet_actions if s.actionParams.isPublic==False]
> ```

private_subnets = [s for s in subnet_actions if not s.actionParams.isPublic]

**Review by apiddubny — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/629)* status: all files reviewed, 1 unresolved discussion (waiting on @nahumtimerman)

**Review by Costya-Y — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/629)* status: all files reviewed, 1 unresolved discussion (waiting on @nahumtimerman)

**Comment by Costya-Y** [comment]
:lgtm:

**Review by Costya-Y — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/629)* status: all files reviewed, 1 unresolved discussion (waiting on @nahumtimerman)

**Review by Costya-Y — APPROVED** [review]

**Pull request merged**
