### PR TITLE
Feature/apiddubny 66 deploy from custom image

### PR DESCRIPTION
**Pull request by apiddubny**
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/172)

### CODE REVIEW

**Comment by alexazarh** [comment]
Reviewed 23 of 30 files at r1.
Review status: 19 of 26 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/azure/common/converters/resource_context.py, line 37 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmpBRzmbvHHt2MS4yE:-KWmpBRzmbvHHt2MS4yF:b-hq2hl6) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/common/converters/resource_context.py#L37)):*
> ```Python
>         deployed_resource.image_publisher = resource.attributes['Image Publisher']
>         deployed_resource.image_offer = resource.attributes['Image Offer']
>         deployed_resource.image_sku = resource.attributes['Image SKU']
> ```

looks like the "Image SKU/Offer/Publisher" properties shouldn't be part of the base?

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 72 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvEbZ-rwgnzu1ga2g:-KWmvEbZ-rwgnzu1ga2h:bbx113a) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L72)):*
> ```Python
>             account_key = self._cached_account_keys[cached_key]
>         else:
>             with self._lock:
> ```

this lock is shared between different cached objects. we should create a separate locker object for each cached object that we want to synchronize. Its important for performance.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 74 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmv1zmkLfyp0JvvE3Z:-KWmv1zmkLfyp0JvvE3_:b5j55yl) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L74)):*
> ```Python
>             with self._lock:
>                 try:
>                     account_key = self._cached_account_keys[cached_key]
> ```

This is an anti-pattern. Please change the implementation with another if statement inside the lock

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 99 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvX7GStDWBqYrF3Mj:-KWmvX7GStDWBqYrF3Mk:b5j55yl) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L99)):*
> ```Python
>                 try:
>                     file_service = self._cached_file_services[cached_key]
>                 except KeyError:
> ```

This is an anti-pattern. Please change the implementation with another if statement inside the lock

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 126 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvYtcvLDlPs3_udn6:-KWmvYtcvLDlPs3_udn7:b5j55yl) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L126)):*
> ```Python
>                 try:
>                     blob_service = self._cached_blob_services[cached_key]
>                 except KeyError:
> ```

This is an anti-pattern. Please change the implementation with another if statement inside the lock

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 196 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvhNvT9msETGASwps:-KWmvhNvT9msETGASwpt:bzib4x4) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L196)):*
> ```Python
>         storage_name = parsed_blob_url.netloc.split('.', 1)[0]
> 
>         return storage_name, container_name, blob_name
> ```

we need to return an object instead of returning a tuple.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 246 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvuBUm-wpYVSEbGoa:-KWmvuBUm-wpYVSEbGob:b-148xrp) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L246)):*
> ```Python
>                     break
>                 else:
>                     time.sleep(1)
> ```

A sleep of 1 second is too low. Its better to increase this to 10 sec at least.
And its better to refactor the waiter so we will have a BlobCopyWaiter class.

---

*[package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, line 175 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmyLKQ4jhaLRm6CpLU:-KWmyLKQ4jhaLRm6CpLV:b605lss) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py#L175)):*
> ```Python
>         container_name_copy_to = "{}{}".format(self.CUSTOM_IMAGES_CONTAINER_PREFIX, container_name)
> 
>         image_urn = self.storage_service.copy_blob(
> ```

The call to this method should be synchronized to make sure we are not copying the same image more than once at the same time. And if we have more than one custom image in the reservation we should be able to copy both of them at the same time. So we probably need to implement a generic locker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/172)*

**Comment by apiddubny** [comment]
Review status: 19 of 26 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 196 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvhNvT9msETGASwps:-KWqqJNjTnQoszZGP-yD:b-7enudd) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L196)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> we need to return an object instead of returning a tuple.
</details>
do you mean one more model for this?
why not tuple? it's pretty simple function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/172)*

**Comment by apiddubny** [comment]
Review status: 19 of 26 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 246 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvuBUm-wpYVSEbGoa:-KWr-OOJHCDupF29qFfW:b2iottt) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L246)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> A sleep of 1 second is too low. Its better to increase this to 10 sec at least.
> And its better to refactor the waiter so we will have a BlobCopyWaiter class.
</details>
I think that separate BlobCopyWaiter class isn't needed here. This waiter is directly related to the Blob copy operation, because it have direct calls to the blob service, it is not some common azure task. So I think it can be just a function under the storage service.

 What do you think about this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/172)*

**Comment by apiddubny** [comment]
Review status: 18 of 26 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/azure/common/converters/resource_context.py, line 37 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmpBRzmbvHHt2MS4yE:-KWr2dFMFvqp5aoRYwgU:b-896fix) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/common/converters/resource_context.py#L37)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> looks like the "Image SKU/Offer/Publisher" properties shouldn't be part of the base?
</details>
Done.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 72 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvEbZ-rwgnzu1ga2g:-KWr3IDef4lg4PR8aYoH:b-896fix) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L72)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> this lock is shared between different cached objects. we should create a separate locker object for each cached object that we want to synchronize. Its important for performance.
</details>
Done.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 74 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmv1zmkLfyp0JvvE3Z:-KWr3LyPxsI5cKjcMPsg:b-896fix) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L74)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> This is an anti-pattern. Please change the implementation with another if statement inside the lock
</details>
Done.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 99 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvX7GStDWBqYrF3Mj:-KWr3NHqNMWZp4J3NOxT:b-896fix) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L99)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> This is an anti-pattern. Please change the implementation with another if statement inside the lock
</details>
Done.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 126 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvYtcvLDlPs3_udn6:-KWr3NvM6yvaM6AFB_Xf:b-896fix) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L126)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> This is an anti-pattern. Please change the implementation with another if statement inside the lock
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/172)*

**Comment by alexazarh** [comment]
Reviewed 2 of 2 files at r2.
Review status: 20 of 26 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 196 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvhNvT9msETGASwps:-KX-vyYZaCDYJd3xNBbi:b-d0cby9) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L196)):*
<details><summary><i>Previously, apiddubny (Anthony Piddubny) wrote…</i></summary>
> do you mean one more model for this?
> why not tuple? it's pretty simple function
</details>
Because we are trying to avoid using tuples as return value as a development methodology. It makes code harder to maintain and harder to debug. And the calling method must know the exact order of the returned parameters which is not good.
If a method returns more than one value than we want to add a model for this.

---

*[package/cloudshell/cp/azure/domain/services/storage_service.py, line 246 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/172#-KWmvuBUm-wpYVSEbGoa:-KX-zL7rzYhYzQAFY9Vf:b-8ayu6x) ([raw file](https://github.com/qualisystems/azure-shell/blob/c3e34ed812afa0857995058618fc0eb7e53693e8/package/cloudshell/cp/azure/domain/services/storage_service.py#L246)):*
<details><summary><i>Previously, apiddubny (Anthony Piddubny) wrote…</i></summary>
> I think that separate BlobCopyWaiter class isn't needed here. This waiter is directly related to the Blob copy operation, because it have direct calls to the blob service, it is not some common azure task. So I think it can be just a function under the storage service.
> 
>  What do you think about this?
</details>
Agree

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/172)*

**Pull request merged**
