### PR TITLE
Feature/apiddubny 36 handle inbound ports nsg configuration

### PR DESCRIPTION
**Pull request by apiddubny**
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/azure-shell/84)

### CODE REVIEW

**Comment by GilGald** [comment]
*[package/cloudshell/cp/azure/domain/services/security_group.py, line 69 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/84#-KV0iHzlCS1GgVEpqMsV:-KV0iHzlCS1GgVEpqMsW:btj265e) ([raw file](https://github.com/qualisystems/azure-shell/blob/5f5a8ffbbdd100d04f8339bdba5d8d21ac35d695/package/cloudshell/cp/azure/domain/services/security_group.py#L69)):*
> ```Python
>         :param group_name: resource group name (reservation id)
>         :param security_group_name:
>         :param inbound_rules:
> ```

What's the type of this ?(inboud_rules)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/84)*

**Comment by GilGald** [comment]
*[package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, line 63 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/84#-KV0k98Zy2URq_8nPW2j:-KV0k98Zy2URq_8nPW2k:b-ggggul) ([raw file](https://github.com/qualisystems/azure-shell/blob/5f5a8ffbbdd100d04f8339bdba5d8d21ac35d695/package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py#L63)):*
> ```Python
>             last_priority=last_priority)
> 
>         if inbound_rules:
> ```

This should be moved upper in the method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/84)*

**Comment by GilGald** [comment]
Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, line 61 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/84#-KV0mCQ6d30w51Q06ol4:-KV0mCQ6d30w51Q06ol5:b-5fecgl) ([raw file](https://github.com/qualisystems/azure-shell/blob/5f5a8ffbbdd100d04f8339bdba5d8d21ac35d695/package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py#L61)):*
> ```Python
>         inbound_rules = RulesAttributeParser.parse_port_group_attribute(
>             ports_attribute=azure_vm_deployment_model.inbound_ports,
>             last_priority=last_priority)
> ```

the next available priority discovery step should be a critical section

---

*[package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, line 63 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/84#-KV0k98Zy2URq_8nPW2j:-KV0kNdES6znBS1_Gkis:bffxegz) ([raw file](https://github.com/qualisystems/azure-shell/blob/5f5a8ffbbdd100d04f8339bdba5d8d21ac35d695/package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py#L63)):*
<details><summary><i>Previously, GilGald wrote…</i></summary>
> This should be moved upper in the method
</details>
we should call the api only if we have valid rules

---

*[package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, line 105 at r1](https://reviewable.io:443/reviews/qualisystems/azure-shell/84#-KV0kra0_2lqom_l0rNr:-KV0kra0_2lqom_l0rNs:b-6mt6qb) ([raw file](https://github.com/qualisystems/azure-shell/blob/5f5a8ffbbdd100d04f8339bdba5d8d21ac35d695/package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py#L105)):*
> ```Python
>         all_networks = self.network_service.get_virtual_networks(network_client, group_name)
> 
>         self._validate_resource(all_networks, group_name, "virtual network")
> ```

Shouldn't be generic take a look at the validation factory

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/84)*

**Comment by alexazarh** [comment]
Reviewed 3 of 7 files at r2, 2 of 6 files at r3, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[package/cloudshell/cp/azure/azure_shell.py, line 44 at r6](https://reviewable.io:443/reviews/qualisystems/azure-shell/84#-KV_elA4tyv-Zkwiuj6-:-KV_elA5pKDITgX7mfV-:b-4adp8a) ([raw file](https://github.com/qualisystems/azure-shell/blob/fa955b3dd6cd5101c072500be2d4418e5ab38ff9/package/cloudshell/cp/azure/azure_shell.py#L44)):*
> ```Python
>         self.key_pair_service = KeyPairService()
>         self.security_group_service = SecurityGroupService()
>         self.lock = Lock()
> ```

This lock is not used anywhere, lets remove it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/84)*

**Comment by alexazarh** [comment]
Reviewed 1 of 1 files at r8.
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/84)*

**Comment by alexazarh** [comment]
Reviewed 1 of 2 files at r7.
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/84)*

**Comment by alexazarh** [comment]
Reviewed 1 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/84)*

**Comment by GilGald** [comment]
*[package/cloudshell/cp/azure/azure_shell.py, line 44 at r2](https://reviewable.io:443/reviews/qualisystems/azure-shell/84#-KVJfIa5jfEhXeGg67OB:-KVJfIa5jfEhXeGg67OC:bq6xx74) ([raw file](https://github.com/qualisystems/azure-shell/blob/07f31a47a1b23dc7004fcc8afc1725e53d3556c5/package/cloudshell/cp/azure/azure_shell.py#L44)):*
> ```Python
>         self.key_pair_service = KeyPairService()
>         self.security_group_service = SecurityGroupService()
>         self.lock = Lock()
> ```

where this is used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/azure-shell/84)*

**Pull request merged**
